/* generated by port/mktiles.py from the NetHack tiles - do not edit */
#define TILES_PER_ROW 32
static const short mon_tile[] = {217,128,133,150,130,168,44,73,110,182,130,65,290,69,74,294,102,220,220,225,105,231,236,68,242,250};
static const short class_tile[] = {346};
static const short weap_tile[] = {468,449,478,413,429,450,419,420,422};
static const short armor_tile[] = {531,529,528,527,525,521,522,518};
static const short mm_tile[] = {-1};
static const short relic_tile[] = {-1};
static const short food_tile[] = {-1};
static const short terrain_tile[128] = {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,920,900,938,904,894,946,-1,-1,-1,-1,-1,-1,897,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,947,-1,944,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,896,-1,950,-1,932,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,931,-1,935,945,-1};
static const short generic_tile[128] = {-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,403,-1,-1,-1,-1,-1,-1,-1,397,835,-1,400,-1,-1,406,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,690,401,-1,399,-1,404,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,398,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1};
#define POTION_TILES 694
#define POTION_NTILES 25
#define SCROLL_TILES 720
#define SCROLL_NTILES 41
#define RING_TILES 570
#define RING_NTILES 28
#define WAND_TILES 807
#define WAND_NTILES 28
#define T_HWALL 880
#define T_VWALL 879
#define T_TL 881
#define T_TR 882
#define T_BL 883
#define T_BR 884
#define T_HDOOR 892
#define T_VDOOR 891
#define T_FLOOR 897
#define T_CORR 900
